Assignment = Concatenation AssignmentOperator Expression ";";

AssignmentOperator = 
   "=" | (* Assign, but take fixed-point format into account *)
  ":=" | (* Assign without bit-weight (straight assign) *)
  "@=" | (* Assign without bit-weight (straight assign) *)
  "+=" | (* Add and assign *)
  "-=" | (* Subtract and assign *)
  "*=" | (* Multiply and assign *)
  "/=" | (* Divide and assign *)
  "%=" | (* Modulus and assign *)
  "&=" | (* Bitwise AND and assign *)
  "|=" | (* Bitwise OR and assign *)
  "^=" | (* Bitwise XOR and assign *)
 "<<=" | (* Shift left and assign *)
 ">>=" ; (* Shift right and assign *)
(*----------------------------------------------------------------------------*)

Expression     = LogicalOR      [ "?" Primary ":" Primary];
LogicalOR      = LogicalAND     { "||"                      LogicalAND    };
LogicalAND     = BitwiseOR      { "&&"                      BitwiseOR     };
BitwiseOR      = BitwiseXOR     {("|"  | "~|")              BitwiseXOR    };
BitwiseXOR     = BitwiseAND     {("^"  | "~^")              BitwiseAND    };
BitwiseAND     = Equality       {("&"  | "~&")              Equality      };
Equality       = Relational     {("==" | "!=")              Relational    };
Relational     = Shift          {("<"  | ">" | "<=" | ">=") Shift         };
Shift          = Additive       {("<<" | ">>")              Additive      };
Additive       = Multiplicative {("+"  | "-" )              Multiplicative};
Multiplicative = Replication    {("*"  | "/" | "%")         Replication   };

Replication   = Concatenation ["\" Primary];
Concatenation = Cast {":" Cast};

Cast       = Reduction [FP_Cast];
FP_Cast    = "'" (Identifier | Literal | ("(" Primary ["," Primary] ")"));
Reduction  = ["&" | "~&" | "|" | "~|" | "^" | "~^" | "!"] Array;

Array = ("@{" Expression {"," Expression} "}")
      | (Unary ["->" Unary ["#" Unary]]);

Unary   = {"-" | "~"} Postfix;
Postfix = Primary {
           "["  SliceList      "]" | (* Slice *)
           "(" [ParameterList] ")" | (* Function call *)
           "."  Identifier         | (* Member reference *)
           "++"                    | (* Increment *)
           "--"                      (* Decrement *)
          };

Primary = Identifier | Literal | String | ("(" Expression ")");

SliceList     = ":" | (Array {"," Array});
ParameterList = Expression {"," Expression};
(*----------------------------------------------------------------------------*)

