#ifndef MemoryTable_h
#define MemoryTable_h
//------------------------------------------------------------------------------

#include "gmp.h"
//------------------------------------------------------------------------------

/** @todo Is this required in the back-end?  Or can it be directly in the HDL?
          If it is not in the back-end, how to include the .mif (or other
          memory initialisation) file?
          - This must be generic - maybe similar to HDL.h, but for memory
            initialisation instead?
*/

// This is much more complicated... Implement later...
// For now, internal only is sufficient.
struct MEMORY_TABLE{
  enum TYPE{
    Internal
    // DDR,
    // SRAM,
  } Type;
};

// - These are also used for FIFO and shift registers -- this block forms a
//   component of the FIFO or shift register.
// - Dual-port always have two separate clock ports (which could be connected
//   to the same clock)
struct MEMORY_INTERNAL{
  enum TYPE{
    ROM_1,  // ROM 1-port
    ROM_2,  // ROM 2-port
    RAM_1,  // RAM 1-port
    RAM_2,  // RAM 2-port (full)
    RAM_R_W // RAM 2-port (simple)
  } Type;

  // Mixed-width ports must be generated by the vendor software
  unsigned Width; // Number of bits per word
  unsigned Depth; // Number of words

  mpz_t* Contents; // Array of contents.  Null => don't care / empty

  MEMORY_INTERNAL();
~MEMORY_INTERNAL();
};
//------------------------------------------------------------------------------

#endif
//------------------------------------------------------------------------------
